### ISSUE TITLE
Bug in layout generator - wall.py

### ISSUE THREAD

**Issue by TRhode** [zestyping/openpixelcontrol#33]
I'm working on a OPC LED project ( https://github.com/DecentralVan/sidewalk ) and I came across a bug in the python layout generator /layouts/wall.py/ ----> It creates rows that alternate direction. 

the python code is: 

```
spacing = 0.11  # m
lines = []
for c in range(-12, 13):
    rs = [range(50), reversed(range(50))][c % 2]
    for r in rs:
        lines.append('  {"point": [%.2f, %.2f, %.2f]}' %
                     (c*spacing, 0, (r - 24.5)*spacing))
print '[\n' + ',\n'.join(lines) + '\n]'
``` 
I replaced it with coffee-script code: 
```
spacing = 0.08

cols = [-6..6]  #13 cols
rows = [-30..31] #62 rows

lines = []
for c in cols
  for r in rows
    lines.push
      "point" : [c*spacing,0,r*spacing]

json = JSON.stringify lines

# From the command line, create a layout by
# use coffee <this file>  >  <destinationJsonFile>
console.log json
```

**Comment by zestyping** [comment]
Interesting that it wasn't clear that the alternation was intentional. :)
 When a matrix of these addressable LEDs is wired up, the rows usually
alternate direction so that they can be connected all in one long chain.

**Comment by zestyping** [comment]
Really cool to see what you're doing with OPC though! :)   Do you happen to
have any videos?

**Comment by TRhode** [comment]
Ok cool (we connected each row to an individual pin on the fadecandy boards). We'll take some videos of it soon :) and I'll send you links
